name: after_first_build
description: A packages that provides a callback that is executed after the first build or after the next frame.
version: 0.0.1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.3.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
