name: base_text_field
description: A packages that creates a declarative api for flutters TextField
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.3.1"

dependencies:
  flutter:
    sdk: flutter

  after_first_build:
    path: ../../packages/after_first_build

dev_dependencies:
  flutter_test:
    sdk: flutter
